function show(){
  movie=document.getElementById("moviename").value;
  if(movie=="")
  {
    document.getElementById("validator").style.display="block";
    document.getElementById("display-data").style.display="none";
    document.getElementById("input").style.position="absolute";
    document.getElementById("footer").style.position="fixed";
    document.getElementById("error").style.display="none";
  }
  else
  {
    document.getElementById("validator").style.display="none";
    var request=new XMLHttpRequest();
    url="http://www.omdbapi.com/?t="+movie+"&apikey=d775a4c8";
    request.open("GET",url,true);
    
    request.onreadystatechange=function(){
    if(request.readyState==4&&request.status==200){
      moviedata=JSON.parse(request.responseText);
      if(moviedata.Title!=undefined)
      {
      document.getElementById("movie-title").innerHTML=moviedata.Title;
      document.getElementById("poster").src=moviedata.Poster;
      document.getElementById("released").innerHTML=moviedata.Released;
      document.getElementById("runtime").innerHTML=moviedata.Runtime;
      document.getElementById("language").innerHTML=moviedata.Language;
      document.getElementById("genre").innerHTML=moviedata.Genre;
      document.getElementById("director").innerHTML=moviedata.Director;
      document.getElementById("actors").innerHTML=moviedata.Actors;
      document.getElementById("writers").innerHTML=moviedata.Writer;
      document.getElementById("imdb").innerHTML=moviedata.imdbRating;
      document.getElementById("plot").innerHTML=moviedata.Plot;
      document.getElementById("awards").innerHTML=moviedata.Awards;
      document.getElementById("display-data").style.display="block";
      document.getElementById("footer").style.display="block";
      document.getElementById("input").style.position="relative";
      document.getElementById("footer").style.position="relative";
      document.getElementById("error").style.display="none";
      }
      else
      {
        document.getElementById("input").style.position="relative";
        document.getElementById("display-data").style.display="none";
        document.getElementById("error").style.display="block";
        document.getElementById("footer").style.position="fixed";
      }
    }
   };
   request.send();
  }
}